### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#20]

**Comment by LiamRiddell** [comment]
I ran some performance tests locally using BenchmarkDotNet. Here's the results.

Mean   : Arithmetic mean of all measurements
Error  : Half of 99.9% confidence interval
StdDev : Standard deviation of all measurements
Median : Value separating the higher half of all measurements (50th percentile)
1 us   : 1 Microsecond (0.000001 sec)

# Version 1 - Austin
|             Method |     Mean |    Error |   StdDev |
|------------------- |---------:|---------:|---------:|
|   TryParseDocument | 37.64 ms | 2.538 ms | 7.483 ms |
|      ParseDocument | 38.77 ms | 2.549 ms | 7.515 ms |
| ParseDocumentAsync | 38.24 ms | 2.157 ms | 6.360 ms |

# Version 2

|                                Method |       Mean |    Error |    StdDev |     Median |
|-------------------------------------- |-----------:|---------:|----------:|-----------:|
|     Render_Template_Amario_Beautified | 1,170.1 us | 52.85 us | 154.18 us | 1,103.5 us |
|       Render_Template_Amario_Minified | 1,065.5 us | 21.23 us |  54.03 us | 1,053.5 us |
| Render_Template_ManyHeroes_Beautified |   780.1 us |  8.21 us |   7.27 us |   779.2 us |
|   Render_Template_ManyHeroes_Minified |   771.8 us | 10.07 us |   9.42 us |   772.7 us |

**Comment by SebastianStehle** [comment]
Nice :)...I hope you are going to submit that ;)

**Comment by LiamRiddell** [comment]
> Nice :) ... I hope you are going to push that ;)
> 
> I have analyzed that with dotTrace, but the majority of time is spent with the StringBuilder. No idea how to optimize this further.

I've created PR now. I'm gonna create new branch for the xml entity issue.
