### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#26]
@LiamRiddell  Do you know how they run tests in mjml. I can hardly find anything. It seems like they have no tests at all or at least not part of the CI.

**Comment by LiamRiddell** [comment]
I too, came to the same conclusion when trying to research MJML. To me it seems they use multi-device testing internally then when they get it to a releasable state they then deploy to component git repository. The second part of the lifecycle is the feedback from community via development branches. I think the combination of the both is how they've managed to "test". Again, I too struggled to find concrete evidence of any unit testing.

**Comment by SebastianStehle** [comment]
But this is a weird process for an open source project.

**Comment by SebastianStehle** [comment]
I also do not like our unit tests so far. They are dependent on minor things like whitespaces and orders of attributes. Perhaps we render the components standalone. If we could find a html parser that has some equality process, we could just use that instead.

**Comment by LiamRiddell** [comment]
> I also do not like our unit tests so far. They are dependent on minor things like whitespaces and orders of attributes. Perhaps we render the components standalone. If we could find a html parser that has some equality process, we could just use that instead.

I agree, this was one of the approaches that I thought about when I was going to introduce unit testing into MJML.NET. It's really the only way of guranting structure is correct.

**Comment by SebastianStehle** [comment]
If there is no test we could perhaps use chromatic. I am not sure if it works, but we could do this:

1. Render several templates with MJML and MJML.NET.
2. Compare the results on several screen sizes.

Does not cover browsers and so on, but better than nothing.

About Chromatic: https://www.chromatic.com/features/test

**Comment by LiamRiddell** [comment]
I think implementing as much testing as possible is the best approach. I like this idea. I believe this is similar to how MJML team do it.
