### ISSUE TITLE
mj-button

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#3]

**Comment by LiamRiddell** [comment]
@SebastianStehle I'm happy to pick this component up.

**Comment by SebastianStehle** [comment]
I see that you also need values like getShorthandAttrValue ... I am working on this right now.

**Comment by LiamRiddell** [comment]
> I see that you also need values like getShorthandAttrValue ... I am working on this right now.

Appreciate that, I've nearly got initial draft complete. Minus the attribute work which I'll update now.

**Comment by LiamRiddell** [comment]
@SebastianStehle Question, what's the best approach to getting the text content of the button? I tried using `RenderChildren` but it doesn't pick up Text nodes.

**Comment by SebastianStehle** [comment]
Yes, exactly.

**Comment by SebastianStehle** [comment]
I have pushed my changes with mj-images. Have forgotten to create a PR :(

**Comment by LiamRiddell** [comment]
> I have pushed my changes with mj-images. Have forgotten to create a PR :(

No problem! It shouldn't affect anything!
