### ISSUE TITLE
Rust Wrapper

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#34]
I just found this: https://github.com/jdrouet/mrml

Could be worth to just make rust wrapper. I do not fully understand rust, but in theory we could be still faster. First because we would not have the overhead of calling a wrapper and I am not sure how good the renderer is there. Seems to be a lot of sub allocations, but not sure.

**Comment by LiamRiddell** [comment]
Personally, I believe we have a unique approach which we could really optimize and have a true native experience for MJML optimized compilation. While Rust is quick I believe if we start wrapping it and having to start sub processes or marshalling it could lead to another non-native solution.

I believe the best approach would be to continue our version (as we're nearly there in terms of the core subset of components) and see the performance. If the performance is way better, we could reach out to the rust project owner to re-implement our approach for even faster compilation. 

I'm personally not a fan of wrappers, which hand off to another executable or loading unmanaged code.

**Comment by SebastianStehle** [comment]
Sounds good

**Comment by SebastianStehle** [comment]
Btw: I have tested a small wrapper and rust takes around 2.2ms for amario:

```
21.3506
2.0836
2.2084
2.0636
2.0526
2.3086
2.007
2.1208
1.9797
2.2234
2.0732
2.2368
2.1503
2.251
2.0719
2.2062
2.0711
2.3133
2.2634
2.5704

```

**Comment by LiamRiddell** [comment]
I'm currently running benchmarks for all the templates. I will be publishing to readme soon.

**Comment by SebastianStehle** [comment]
But it is not fair if we do not support all tags yet.

**Comment by LiamRiddell** [comment]
Yeah, I'm mainly doing it to extend the benchmarking project and once we're mostly feature complete before release we can run the benchmarks again.
