### ISSUE TITLE
Getting attribute values

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#35]
Hi,

getting attribute values is relatively expensive. You have to get the attribute from the node, classes, fallbacks and so on and then validate it.

To optimize it we have 2 alternatives:

1. Ensure that we ask for every property only once (We can write code for that in debug mode): Best performance
2. Cache the result: Less performance, but a little bit easier code.

**Comment by LiamRiddell** [comment]
@SebastianStehle, I too agree with approach 1. What do you mean by we can write code in debug mode?

**Comment by SebastianStehle** [comment]
We can write some code that tracks how often GetAttribute() is invoked and throws an exception if it happens more than once. But we can do it later, if we see that this could improve performance.

**Comment by LiamRiddell** [comment]
> We can write some code that tracks how often GetAttribute() is invoked and throws an exception if it happens more than once. But we can do it later, if we see that this could improve performance.

Appreciate you taking the time to explain this. Yeah, I like the idea of this. Again, using profiling and experience we should be able to squeeze out lots of performance from across the board.

**Comment by SebastianStehle** [comment]
With the source generator it is obsolete now.
