### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#37]
Just a list of performance improvements we could implement.

* [x] Ensure that we query each attribute only once or cache the results.
* [x] Implement a custom stack that reuses the elements.
* [x] Check the performance implication of XmlReader.Subtree.

**Comment by LiamRiddell** [comment]
Once we're more feature complete we should do some stress tests on templates with profiling enabled to find the pain spots and from there we can see if there is any options for optimisation.

**Comment by SebastianStehle** [comment]
Absolutely, I just wrote down my ideas, so I do not forget them.
