### ISSUE TITLE
Conditional Tags

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-test#41]
Change all instances of hardcoded Conditional Tags being injected via `renderer.Content("<...>")` to use the new extension methods.

**Comment by SebastianStehle** [comment]
I think mjml has a process to eliminate duplicate conditional tags. It makes testing harder, because the output of mjml does not always match to the result.

So I guess we have to put this into the renderer somehow.

renderer.StartConditional(...);

and if a conditional is not ended yet a new start will not be emitted.

**Comment by LiamRiddell** [comment]
> I think mjml has a process to eliminate duplicate conditional tags. It makes testing harder, because the output of mjml does not always match to the result.
> 
> So I guess we have to put this into the renderer somehow.
> 
> renderer.StartConditional(...);
> 
> and if a conditional is not ended yet a new start will not be emitted.

Yes, that is correct. It's an annoyance for testing, I believe it's a part of the post-processing logic of MJML. I wouldn't know what the best approach is for that yet. It would possibly be tracking the state of whether we're already in an open conditional? If so then don't allow opening more? The same logic would possibly go for closing.

**Comment by SebastianStehle** [comment]
> Yes, that is correct. It's an annoyance for testing, I believe it's a part of the post-processing logic of MJML. I wouldn't know what the best approach is for that yet. It would possibly be tracking the state of whether we're already in an open conditional? If so then don't allow opening more? The same logic would possibly go for closing.

Yes, this would be the idea.

**Comment by SebastianStehle** [comment]
I am not so sure if it would make sense to have extension methods for conditional tags. When I look for failed tests, I compare my rendering with markdown and the more transfers I have to do the harder it is.

**Comment by LiamRiddell** [comment]
Agreed, we probably need to bring the `ConditionalTags` into the `renderer` itself due to the above change would require state.

**Comment by SebastianStehle** [comment]
I think it is not possible.

Lets say you have the following calls.

S = StartConditional
E = EndConditional

S
E
S
E

This can only be decided at the last End. Therefore we would have to change the final rendering, which obviously kills performance.

**Comment by LiamRiddell** [comment]
Yeah, I think it would be better to leave it and provide a helper or plugin that can do this on output. Technically speaking, both ours and mjmls will work the same it just means we need to fix tests.

**Comment by SebastianStehle** [comment]
What do you think about my other statement?

I also thought that it would be a good idea to provide helper methods  for conditional statements. But for me it makes it harder to compare the c# with the javascript code. Therefore I am not sure whether it is worth it.

**Comment by LiamRiddell** [comment]
> What do you think about my other statement?
> 
> I also thought that it would be a good idea to provide helper methods for conditional statements. But for me it makes it harder to compare the c# with the javascript code. Therefore I am not sure whether it is worth it.

While I do agree it makes it slightly harder to compare between C# and JS implementation. My concern is the chance of mistakes when constantly rewriting them. Since we introduced helpers it's been lots easier for me to rattle through components without worrying about all the conditionals potentially having a typo. However, it's personal preference.

**Comment by SebastianStehle** [comment]
I would go with the plain mode to be honest. Comparing the render code was a real pain this week ;) ... Usually I would go with the extension methods as well.

**Comment by LiamRiddell** [comment]
Sounds good. Let's leave this till one of the last tasks. As it would be easier to do as a one off task.

**Comment by SebastianStehle** [comment]
Sure
