### ISSUE TITLE
Extensions Helpers

### ISSUE THREAD

**Issue by LiamRiddell** [SebastianStehle/mjml-test#42]
Move NodeExtenstions into the `Mjml.Net.Extensions` name space. Furthermore, include any other Extensions we've got laying around.

**Comment by SebastianStehle** [comment]
Please do not use the "Helpers" namespace for that. because this has a special meaning in this context.

**Comment by LiamRiddell** [comment]
@SebastianStehle, yes, I see the Helpers namespace is used for specific case. We just need to move the `NodeExtensions.cs` from `Mjml.Net.Components` to `Mjml.Net.Extensions`. That way it's functionality falls inline with the namespace.
