### ISSUE TITLE
Write high level tests for a few complex templates?

### ISSUE THREAD

**Issue by SebastianStehle** [SebastianStehle/mjml-test#62]

**Comment by SebastianStehle** [comment]
@LiamRiddell I have pushed a test with Amario template and the test is green :)

I had to make a few bugfixes, but now it works. The only problem are the comments, but thats okay, I guess.

But I realized that we should not use https://mjml.io/ to create our expected html results, because it is not up to date and if you use the current version as a reference your tests can be wrong.

**Comment by LiamRiddell** [comment]
That's good to know! I'm going to add all of the MJML templates to the benchmarking project. As it was good for finding bugs. Furthermore, I may add then to the test runner so we can get all of the output for comparison.

**Comment by SebastianStehle** [comment]
The unit tests writes all htmls to a file already.
